package org.tribot.automation.script.event

import net.runelite.api.GameState
import net.runelite.api.events.ChatMessage
import net.runelite.api.events.MenuOptionClicked
import java.awt.Graphics2D
import java.awt.Point
import java.io.Closeable

/**
 * Central event subscription interface for scripts to react to game, input, and lifecycle events.
 *
 * All registration methods return a [ListenerRegistration] that can be used to unsubscribe.
 * Listeners are automatically cleaned up when the script ends.
 */
interface Events {

    // -- Game events --

    /**
     * Called once per game tick (~600ms).
     *
     * Runs in the client thread.
     */
    fun onGameTick(listener: () -> Unit): ListenerRegistration

    /**
     * Called when the game state changes (e.g. logged in, loading, connection lost).
     *
     * Runs in the client thread.
     */
    fun onGameStateChanged(listener: (GameState) -> Unit): ListenerRegistration

    /**
     * Called every frame before the client renders. Essentially, the "clientside" tick.
     *
     * Runs in the client thread.
     */
    fun onBeforeRender(listener: () -> Unit): ListenerRegistration

    // -- Chat messages --

    /**
     * Called when a chat message is received (game messages, player chat, etc).
     *
     * Runs in the client thread.
     */
    fun onChatMessage(listener: (message: ChatMessage) -> Unit): ListenerRegistration

    // -- Menu events --

    /**
     * Called when a menu option is clicked (e.g. "Walk here", "Attack", "Use").
     *
     * Runs in the client thread.
     */
    fun onMenuOptionClicked(listener: (event: MenuOptionClicked) -> Unit): ListenerRegistration

    // -- Script lifecycle --

    /** Called when the script is about to stop. Use for cleanup. */
    fun onScriptEnding(listener: () -> Unit): ListenerRegistration

    /** Called when the script is paused by the user. */
    fun onScriptPause(listener: () -> Unit): ListenerRegistration

    /** Called when the script is resumed after a pause. */
    fun onScriptResume(listener: () -> Unit): ListenerRegistration

    // -- Breaks --

    /**
     * Called before a break begins. Runs while the script is still active, allowing pre-break actions
     * like logging out or moving to a safe area.
     * @param durationMs the planned break duration in milliseconds
     */
    fun onPreBreakStart(listener: (durationMs: Long) -> Unit): ListenerRegistration

    /**
     * Called when a break officially starts, after the script has been paused.
     * @param durationMs the planned break duration in milliseconds
     */
    fun onBreakStart(listener: (durationMs: Long) -> Unit): ListenerRegistration

    /** Called when a break ends and the script resumes. */
    fun onBreakEnd(listener: () -> Unit): ListenerRegistration

    // -- Painting --

    /** Called each frame to draw custom overlays on the game canvas. */
    fun onPaint(listener: (Graphics2D) -> Unit): ListenerRegistration

    /** Called each frame to draw a custom mouse cursor or mouse-relative overlay. */
    fun onMousePaint(listener: (g: Graphics2D, x: Int, y: Int) -> Unit): ListenerRegistration

    // -- Mouse listeners --

    /** Called when a mouse click occurs. [isBot] is true if the click was generated by the bot. */
    fun onMouseClick(listener: (point: Point, button: Int, isBot: Boolean) -> Unit): ListenerRegistration

    /** Called when the mouse moves. [isBot] is true if the movement was generated by the bot. */
    fun onMouseMove(listener: (point: Point, isBot: Boolean) -> Unit): ListenerRegistration

    /** Called when the mouse is dragged. [isBot] is true if the drag was generated by the bot. */
    fun onMouseDrag(listener: (point: Point, button: Int, isBot: Boolean) -> Unit): ListenerRegistration

    /** Called when a mouse button is released. [isBot] is true if the release was generated by the bot. */
    fun onMouseRelease(listener: (point: Point, button: Int, isBot: Boolean) -> Unit): ListenerRegistration

    // -- Key listeners --

    /** Called when a key is pressed. [isBot] is true if the press was generated by the bot. */
    fun onKeyPressed(listener: (keyCode: Int, isBot: Boolean) -> Unit): ListenerRegistration

    /** Called when a key is typed. [isBot] is true if the event was generated by the bot. */
    fun onKeyTyped(listener: (keyCode: Int, isBot: Boolean) -> Unit): ListenerRegistration

    /** Called when a key is released. [isBot] is true if the release was generated by the bot. */
    fun onKeyReleased(listener: (keyCode: Int, isBot: Boolean) -> Unit): ListenerRegistration

    // -- Input overrides --

    /**
     * Intercepts mouse events before they reach the game client.
     * Return [EventOverride.DISMISS] to block the event, or [EventOverride.SEND] to pass it through.
     */
    fun overrideMouseEvents(listener: (java.awt.event.MouseEvent) -> EventOverride): ListenerRegistration

    /**
     * Intercepts key events before they reach the game client.
     * Return [EventOverride.DISMISS] to block the event, or [EventOverride.SEND] to pass it through.
     */
    fun overrideKeyEvents(listener: (java.awt.event.KeyEvent) -> EventOverride): ListenerRegistration
}

fun interface ListenerRegistration: Closeable {
    fun remove()
    override fun close() = remove()
}

enum class EventOverride {
    SEND,
    DISMISS
}
