package org.tribot.automation.script.core

/**
 * Recognized login screen messages. The set of values intentionally mirrors what
 * the live login flow knows how to react to — see [Login.getLoginMessage].
 */
enum class LoginMessage(val isAuthenticatorMessage: Boolean = false) {
    ALREADY_LOGGED_IN,
    AUTHENTICATOR(isAuthenticatorMessage = true),
    AUTHENTICATOR_INVALID(isAuthenticatorMessage = true),
    AUTHENTICATOR_ALREADY_LOGGED_IN(isAuthenticatorMessage = true),
    AUTHENTICATOR_ERROR_CONNECTING(isAuthenticatorMessage = true),
    AUTHENTICATOR_INVALID_SKILL_TOTAL(isAuthenticatorMessage = true),
    AUTHENTICATOR_LOGIN_LIMITED_EXCEEDED(isAuthenticatorMessage = true),
    AUTHENTICATOR_MEM_WORLD(isAuthenticatorMessage = true),
    AUTHENTICATOR_NO_REPLY(isAuthenticatorMessage = true),
    AUTHENTICATOR_SERVER_OFFLINE(isAuthenticatorMessage = true),
    AUTHENTICATOR_STANDING_IN_MEMBERS(isAuthenticatorMessage = true),
    AUTHENTICATOR_TIMED_OUT(isAuthenticatorMessage = true),
    AUTHENTICATOR_TOO_MANY_ATTEMPTS(isAuthenticatorMessage = true),
    AUTHENTICATOR_WORLD_FULL(isAuthenticatorMessage = true),
    BANNED,
    BETA_WORLD,
    BETA_MOBILE_WORLD,
    FRESH_START_WORLD,
    FRESH_START_PLAYER,
    CONNECTING,
    DISCONNECTED,
    ENTER,
    ERROR_CONNECTING,
    JAGEX_ACCOUNT_FAILED,
    INVALID,
    INVALID_SKILL_TOTAL,
    LOCKED,
    LOGIN_LIMIT_EXCEEDED,
    MEM_WORLD,
    NOT_MEMBER,
    NO_REPLY,
    PVP_WORLD,
    SERVER_OFFLINE,
    STANDING_IN_MEMBERS,
    TIMED_OUT,
    TOO_MANY_ATTEMPTS,
    TOO_MANY_ATTEMPTS_USE_LAUNCHER,
    UPDATED,
    UPDATE_IN_PROGRESS,
    WORLD_FULL,
    ACCEPT_DOCUMENTS_PROMPT,
    DECLINED_DOCUMENTS,
    PLAY_NOW,
    SET_DATE_OF_BIRTH,
    BOT_BUSTING_WORLD,
    HIGH_RISK_WORLD,
    USER_NAME_NOT_SET,
}
